RestrictedFunctionSpace: Added in changes to Dataset / Set for use in RestrictedFunctionSpace in firedrake
OP2/PyOP2 pull request #716
Opened 2024-02-26 15:51 UTC by emmarothwell1

Is a part of the following pull request: [https://github.com/firedrakeproject/firedrake/pull/3426](url)

This gives sets an additional size, called constrained size. This is then used to create the correct layout_vec for restricted spaces.
There's also some signature data being passed through the global kernel as well to distinguish between restricted and unrestricted spaces.

2024-02-28 16:51 UTC, dham requested changes
This is good except for naming quibbles.

2024-02-28 16:51 UTC, dham commented on pyop2/global_kernel.py
> +                 form_signature=None):
```suggestion
                 signature=None):
```
We try to avoid finite-element specific things at OP2 level.

2024-02-28 16:51 UTC, dham commented on pyop2/types/dataset.py
> +        size = (self.size * self.cdim - self.set.constrained_size, None)
```suggestion
        size = ((self.size - self.set.constrained_size) * self.cdim, None)
```

2024-02-28 16:51 UTC, dham commented on pyop2/types/set.py
> +    def __init__(self, size, name=None, halo=None, comm=None, constrained_nodes=0):
```suggestion
    def __init__(self, size, name=None, halo=None, comm=None, constrained_size=0):
```

2024-02-28 16:51 UTC, dham commented on pyop2/types/set.py
> +        self._constrained_size = constrained_nodes
```suggestion
        self._constrained_size = constrained_size
```

2024-04-25 14:28 UTC, emmarothwell1 commented on pyop2/types/set.py
> +        """Set size, owned elements."""
```suggestion
        """Set size, owned constrained elements."""
```

2024-04-25 14:29 UTC, dham approved these changes

2024-04-26 21:34 UTC, merged